[package]
name = "battleship"
version = "0.1.0"
authors = ["Tschuck <tobias.winkler@outlook.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
